version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: hw8
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:admin@postgres_db/hw8
      REDIS_URL: redis://redis_cache:6379
      JWT_SECRET: "your_secret_key"
      JWT_ALGORITHM: "HS256"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
