"""Add user role

Revision ID: ad31f25bcd91
Revises: f4eff00d821e
Create Date: 2025-02-09 19:55:23.466250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad31f25bcd91"
down_revision: Union[str, None] = "f4eff00d821e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = sa.Enum("user", "admin", name="user_role")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("users", sa.Column("role", user_role_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")

    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
